### ISSUE TITLE
Single proposal view improvements

### ISSUE THREAD

**Issue by 1emu** [decentraland/governance#1263]
![Image](https://user-images.githubusercontent.com/467712/268115092-0a37c392-8a7a-4ba4-9dac-64d9f3f9d8f6.png)

- [x] begin with implementing the floating bar
- [x] floating bar has 2 alternatives depending on proposal type
- [x] proposal status to determine styling for specific elements
- [x] hero color determined by proposal type and state
- [x] single proposal view to make use of bigger viewport
- [x] previous/old container width (2 column layout) to be used on smaller screens
- [x] "proposal detail" block to be placed fixed on a new left column for bigger screens
- [x] new scroll down interaction: display a new heading

![Image](https://user-images.githubusercontent.com/467712/268115246-fc41f6bf-7200-450c-aa39-396d70b1d655.png)

if reactions are not available for the proposal at hand, simply move the comments link over

while the proposal is open, use bright colors for the hero. otherwise, fallback to a dull-er hero

![Image](https://user-images.githubusercontent.com/467712/268115445-fbc31b22-7bdd-4a28-b2c4-f1f82717ed50.png)

scroll down interaction makes a fixed bar appear at the top of the screen

![Image](https://user-images.githubusercontent.com/467712/268115583-43f70bb9-7fb7-459b-bbcb-16ea4f0439dd.png)

**Comment by ncomerci** [comment]
https://github.com/decentraland/governance/pull/1287
