### ISSUE TITLE
New Grant Categories

### ISSUE THREAD

**Issue by ginocingolani** [decentraland/governance#644]
This issue is about creating new categories and requirements for grant requests.

- [ ] Update new Categories as per [this document ](https://www.notion.so/dcl-dao/PRD-Grant-Restructuring-Project-88f295bef31b4426bf40d53371c40489#af321f076f05438ca5ceb0d2229609d1 )
- [ ] Update grant request form with relevant questions per each category (Content TBD)
- [ ] Update Decentraland Docs with new requirements

See more info [here](https://www.notion.so/dcl-dao/PRD-Grant-Restructuring-Project-88f295bef31b4426bf40d53371c40489#b84b2c1ca8b24504bdc14ee0edcfd33e)
